# review-epubmaker向けの設定ファイルの例。
# yamlファイルをReVIEWファイルのある場所に置き、
# 「review-epubmaker yamlファイル」を実行すると、<bookname>.epubファイルが
# 生成されます。
# このファイルはUTF-8エンコーディングで記述してください。

# ブック名(ファイル名になるもの。ASCII範囲の文字を使用)
bookname: book
# 書名
booktitle: 邊做邊學程式語言　以 Ruby 實作 Scheme 處理器
# 著者
aut: 渡辺昌寛
prt: 達人出版会
prt_url:  http://tatsu-zine.com/
edt: 高橋征義
trl: Tsehau Chao
date: 2013-04-16
rights: |
  (C) 2013 Masahiro Watanabe
description: (未定)
# 以下はオプション
# prt: 出版社
# asn: Associated name
# ant: Bibliographic antecedent
# clb: 貢献者
# edt: 編集者
# dsr: デザイナ
# ill: イラストレータ
# pht: 撮影者
# trl: 翻訳者
# date: 刊行日
# rights: 権利表記
# description: ブックの説明
#
# coverfile: カバーページのbody要素内に挿入する内容を記述したファイル名
coverfile: _cover.html
# coverimage: 表紙用画像ファイル
coverimage: cover.jpg
# 固有IDに使用するドメイン
urnid: http://tatsu-zine.com/books/scheme-in-ruby/
# CSSファイル (yamlファイルおよびReVIEWファイルを置いたディレクトリにあること
stylesheet: main.css
# 目次として抽出するレベル
toclevel: 2
# セクション番号を表示するレベル
secnolevel: 3
# review-compileに渡すパラメータ
params: --stylesheet=main.css --subdirmode
# 目次生成用？
mytoc: true
# 奥付生成用
colophon: true
texstyle: tatsumacro
texdocumentclass: ["jsbook", "oneside,12pt"]
pubhistory: |
  2013年4月16日 v1.0.0版発行
debug: true
